# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1044, 661)
        Form.setStyleSheet("QPushButton#btnNext, QPushButton#btnPrev, QPushButton#btnRefresh {\n"
"    background: transparent;\n"
"    width: 30px; height: 30px;\n"
"}\n"
"\n"
"QPushButton#btnNext {\n"
"    border-image: url(\'static/button/next.png\');\n"
"}\n"
"QPushButton#btnPrev {\n"
"    border-image: url(\'static/button/previous.png\');\n"
"}\n"
"QPushButton#btnRefresh {\n"
"    border-image: url(\'static/button/refresh.png\');\n"
"}\n"
"\n"
"QLineEdit#urlBar {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel#httpsicon {\n"
"    width: 15px; height: 15px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitterMain = QtWidgets.QSplitter(Form)
        self.splitterMain.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMain.setObjectName("splitterMain")
        self.splitterSidebar = QtWidgets.QSplitter(self.splitterMain)
        self.splitterSidebar.setMinimumSize(QtCore.QSize(0, 0))
        self.splitterSidebar.setOrientation(QtCore.Qt.Vertical)
        self.splitterSidebar.setHandleWidth(4)
        self.splitterSidebar.setObjectName("splitterSidebar")
        self.fileView = QtWidgets.QTreeView(self.splitterSidebar)
        self.fileView.setObjectName("fileView")
        self.horizontalFrame = QtWidgets.QFrame(self.splitterMain)
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.horizontalFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalFrame.setLineWidth(1)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.horizontalFrame)
        self.gridLayout_6.setContentsMargins(-1, -1, 1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelLoading = QtWidgets.QLabel(self.horizontalFrame)
        self.labelLoading.setText("")
        self.labelLoading.setObjectName("labelLoading")
        self.gridLayout_6.addWidget(self.labelLoading, 0, 4, 1, 1)
        self.gLayoutBrowser = QtWidgets.QGridLayout()
        self.gLayoutBrowser.setObjectName("gLayoutBrowser")
        self.gridLayout_6.addLayout(self.gLayoutBrowser, 2, 0, 1, 6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPrev = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrev.sizePolicy().hasHeightForWidth())
        self.btnPrev.setSizePolicy(sizePolicy)
        self.btnPrev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPrev.setText("")
        self.btnPrev.setObjectName("btnPrev")
        self.horizontalLayout.addWidget(self.btnPrev)
        self.btnRefresh = QtWidgets.QPushButton(self.horizontalFrame)
        self.btnRefresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRefresh.setText("")
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout.addWidget(self.btnRefresh)
        self.btnNext = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext.sizePolicy().hasHeightForWidth())
        self.btnNext.setSizePolicy(sizePolicy)
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNext.setText("")
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        self.httpsicon = QtWidgets.QLabel(self.horizontalFrame)
        self.httpsicon.setText("")
        self.httpsicon.setObjectName("httpsicon")
        self.horizontalLayout.addWidget(self.httpsicon)
        self.urlBar = QtWidgets.QLineEdit(self.horizontalFrame)
        self.urlBar.setObjectName("urlBar")
        self.horizontalLayout.addWidget(self.urlBar)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.gridLayout.addWidget(self.splitterMain, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
